version: '3'
services:
  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Testing123
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ../:/var/app/
    ports:
      - 3000:3000
    command: tail -f /dev/null
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Testing123
      DATABASE_HOST: database
